### PR TITLE
Added Radio Mast Reference Streams

### PR DESCRIPTION
**Pull request by asantoni**
Hey Mike, we recently published a list of sample streams that are all playing the same content over at Radio Mast. While developing various features for [RSAS](https://www.rocketbroadcaster.com/streaming-audio-server) and Radio Mast, we found it really handy to have these available for QA testing and comparing codecs. We've been sharing this list with developers and hardware manufacturers for QA testing.

These streams are especially handy because there's some rare combinations that are hard to find stable links for, including:

- an Ogg FLAC stream (with a known bit depth), and including in-stream ICY metadata
- HLS streams for MP3 and AAC
- HE-AAC v1 and v2, side-by-side, including low bit-rate versions for comparison

Our site also has links to M3U playlists containing all the streams too, which is sometimes useful for quickly comparing the streams side-by-side. I didn't want to copy one of those playlists into the repo here since we're already keeping it up-to-date upstream, so there's no point in just duplicating it here and risking it becoming outdate.

Anyways, just wanted to share this because I hope it's a useful contribution to your list.

Thanks for your consideration!

### CODE REVIEW

**Comment by mikepierce** [comment]
14July2023-1689387650

**Comment by asantoni** [comment]
Thanks for trying that out and considering this pull request. It turns out you actually found a bug in our CDN, which prevented those HLS streams from being replicated to our cluster that's serving your region. We've fixed the underlying issue and verified the HLS streams are propagating now, so those HLS URLs should be working for you now. I apologize for that!

Would you be willing to reconsider this pull request? Are there any other criteria for inclusion in your list or any way we could improve the pull request?

Thanks!

**Comment by mikepierce** [comment]
no

**Comment by mikepierce** [comment]
> Thanks for trying that out and considering this pull request. It turns out you actually found a bug in our CDN, which prevented those HLS streams from being replicated to our cluster that's serving your region. We've fixed the underlying issue and verified the HLS streams are propagating now, so those HLS URLs should be working for you now. I apologize for that!
> 
> Would you be willing to reconsider this pull request? Are there any other criteria for inclusion in your list or any way we could improve the pull request?
> 
> Thanks!

no

**Pull request closed without merging**
